# Generated by Django 3.0.6 on 2020-06-10 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dstagram',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=100, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dstagram',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mypage.Dstagram', verbose_name='디스타그램'),
        ),
        migrations.AlterField(
            model_name='dstagram',
            name='content',
            field=models.TextField(blank=True, max_length=100, verbose_name='내용'),
        ),
    ]
