# Generated by Django 3.0.6 on 2020-06-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20200610_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='comment_tag', to='mypage.Tag'),
        ),
        migrations.AlterField(
            model_name='dstagram',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dstagram_tag', to='mypage.Tag'),
        ),
    ]
