# Generated by Django 3.0.6 on 2020-06-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_auto_20200610_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='dstagram',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
