# Generated by Django 3.0.6 on 2020-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0006_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='dstagram',
            name='p_type',
            field=models.CharField(choices=[('c', '댓글'), ('p', '포스트')], default='p', max_length=1),
        ),
    ]
