# Generated by Django 3.0.6 on 2020-06-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_dstagram_p_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='p_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mypage.Comment'),
        ),
    ]
