# Generated by Django 3.0.6 on 2020-06-11 07:14

import accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='_user_follow_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='_user_follower_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='media/user_img/default.jpg', upload_to=accounts.models.get_path, verbose_name='사진'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_profile',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
