# Generated by Django 3.0.6 on 2020-06-11 08:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(upload_to=accounts.models.get_path, verbose_name='사진'),
        ),
    ]
